# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  target 'TourApp' do
  source 'https://github.com/CocoaPods/Specs.git'

    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'Firebase/Analytics'
    pod 'Firebase/Auth'
    
    pod 'Firebase/Core'
    pod 'Firebase/Firestore'


# Pods for TourApp
# add the Firebase pod for Google Analytics

# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods


end
